save

diff --git a/capybara b/capybara
--- a/capybara
+++ b/capybara
@@ -59,12 +59,6 @@ capybara checkout snapshot
     (to allow recovery if the source directory disk fails).
 '
 
-if [ "$#" -lt 1 ]
-then
-    printf 'Error: %s' "$usage" 1>&2
-    exit 1
-fi
-
 os="$(uname)"
 
 if [ "$os" = Linux ]
@@ -81,6 +75,70 @@ else
     stat_size_format='%z'
     sha512=sha512
     sha512_make="$sha512"
+fi
+
+
+gather_metadata() {
+tmp_bad_fn="$(mktemp)"
+tmp_stat="$(mktemp)"
+
+find . -type f \( -name '*|*' -o -name '*
+*' \) > "$tmp_bad_fn"
+
+if [ -s "$tmp_bad_fn" ]
+then
+    printf 'Error: capybara: Newline or pipe character in filename(s):\n' 1>&2
+    cat "$tmp_bad_fn" 1>&2
+    exit 1
+fi
+
+find . -type f -exec stat "$stat_option" "$stat_format" '{}' \; \
+    | cut -c 3- > "$tmp_stat"
+
+sqlite3 "$store_dir"/.capybara.db <<EOF
+$dot_settings
+
+DELETE FROM c_stage;
+.import $tmp_stat c_stage
+
+.quit
+EOF
+
+rm "$tmp_bad_fn" "$tmp_stat"
+}
+
+
+load_latest() {
+sqlite3 "$store_dir"/.capybara.db <<EOF
+$dot_settings
+
+DELETE FROM c_latest;
+
+INSERT INTO c_latest
+(filename,
+file_size,
+modified_time,
+perm,
+hash)
+SELECT
+a.filename,
+a.file_size,
+a.modified_time,
+a.perm,
+a.hash
+FROM c_file AS a
+WHERE
+a.snapshot_time = (SELECT Max(b.snapshot_time) FROM c_snapshot AS b);
+
+.quit
+EOF
+}
+
+
+if [ "$#" -lt 1 ]
+then
+    printf 'Error: %s' "$usage" 1>&2
+    exit 1
 fi
 
 
@@ -173,6 +231,47 @@ EOF
 
 
 ###############################################################################
+elif [ "$1" = status ]
+then
+
+if [ "$#" -ne 1 ]
+then
+    printf 'Error: %s' "$usage" 1>&2
+    exit 1
+fi
+
+store_dir="$(cat .capybara_store_location)"
+
+gather_metadata
+load_latest
+
+sqlite3 "$store_dir"/.capybara.db <<EOF
+$dot_settings
+
+SELECT
+'New: ' || a.filename
+FROM c_stage AS a
+WHERE
+a.filename NOT IN (SELECT b.filename FROM c_latest AS b);
+
+SELECT
+'Removed: ' || a.filename
+FROM c_latest AS a
+WHERE
+a.filename NOT IN (SELECT b.filename FROM c_stage AS b);
+
+SELECT
+'Modified: ' || a.filename
+FROM c_stage AS a
+INNER JOIN c_latest AS b
+ON a.filename = b.filename
+AND (a.file_size <> b.file_size OR a.modified_time <> b.modified_time);
+
+.quit
+EOF
+
+
+###############################################################################
 elif [ "$1" = snapshot ]
 then
 
@@ -186,48 +285,15 @@ store_dir="$(cat .capybara_store_location)"
 
 snapshot_time="$(date '+%s')"
 
-tmp_bad_fn="$(mktemp)"
-tmp_stat="$(mktemp)"
 tmp_to_hash="$(mktemp)"
 tmp_hash_result="$(mktemp)"
 tmp_to_copy="$(mktemp)"
 
-find . -type f \( -name '*|*' -o -name '*
-*' \) > "$tmp_bad_fn"
-
-if [ -s "$tmp_bad_fn" ]
-then
-    printf 'Error: %s: Newline or pipe character in filename(s):\n' "$1" 1>&2
-    cat "$tmp_bad_fn" 1>&2
-    exit 1
-fi
-
-find . -type f -exec stat "$stat_option" "$stat_format" '{}' \; \
-    | cut -c 3- > "$tmp_stat"
+gather_metadata
+load_latest
 
 sqlite3 "$store_dir"/.capybara.db <<EOF
 $dot_settings
-
-DELETE FROM c_stage;
-.import $tmp_stat c_stage
-
-DELETE FROM c_latest;
-
-INSERT INTO c_latest
-(filename,
-file_size,
-modified_time,
-perm,
-hash)
-SELECT
-a.filename,
-a.file_size,
-a.modified_time,
-a.perm,
-a.hash
-FROM c_file AS a
-WHERE
-a.snapshot_time = (SELECT Max(b.snapshot_time) FROM c_snapshot AS b);
 
 .echo off
 .changes off
@@ -246,6 +312,7 @@ NOT IN
 
 .quit
 EOF
+
 
 if [ -s "$tmp_to_hash" ]
 then
@@ -322,7 +389,7 @@ END TRANSACTION;
 .quit
 EOF
 
-rm "$tmp_bad_fn" "$tmp_stat" "$tmp_to_hash" "$tmp_hash_result" "$tmp_to_copy"
+rm "$tmp_to_hash" "$tmp_hash_result" "$tmp_to_copy"
 
 
 ###############################################################################
