save

diff --git a/capybara b/capybara
--- a/capybara
+++ b/capybara
@@ -77,40 +77,32 @@ capybara checkout snapshot
 
 os="$(uname)"
 
-if [ "$os" = Linux ]
+gather_metadata() {
+tmp_fn="$(mktemp)"
+tmp_fn_check="$(mktemp)"
+
+find . -type f -print0 > "$tmp_fn"
+
+< "$tmp_fn" tr -d '|\n' > "$tmp_fn_check"
+
+if ! cmp "$tmp_fn" "$tmp_fn_check"
 then
-    stat_option='-c'
-    stat_format='%n|%s|%Y|%a'
-    sha512_make='sha512sum --tag'
-else
-    # BSD
-    stat_option='-f'
-    stat_format='%N|%z|%m|%Lp'
-    sha512_make=sha512
-fi
-
-
-bad_filenames() {
-tmp_bad_fn="$(mktemp)"
-
-find "$1" -type f \( -name '*|*' -o -name '*
-*' \) > "$tmp_bad_fn"
-
-if [ -s "$tmp_bad_fn" ]
-then
-    printf 'Error: capybara: Newline or pipe character in filename(s):\n' 1>&2
-    cat "$tmp_bad_fn" 1>&2
-    rm "$tmp_bad_fn"
+    printf 'Error: capybara: Newline or pipe character in filename\n' 1>&2
+    rm "$tmp_fn" "$tmp_fn_check"
     exit 1
 fi
-}
 
-
-gather_metadata() {
 tmp_stat="$(mktemp)"
 
-find . -type f -exec stat "$stat_option" "$stat_format" '{}' \; \
-    | cut -c 3- > "$tmp_stat"
+if [ "$os" = Linux ]
+then
+    < "$tmp_fn" xargs -0 -n 100 -P 1 stat -c '%n|%s|%Y|%a' \
+        | sed -E 's|^\./||' > "$tmp_stat"
+else
+    # BSD
+    < "$tmp_fn" xargs -0 -n 100 -P 1 stat -f '%N|%z|%m|%Lp' \
+        | sed -E 's|^\./||' > "$tmp_stat"
+fi
 
 sqlite3 "$store_dir"/.capybara.db <<EOF
 $dot_settings
@@ -121,7 +113,7 @@ DELETE FROM c_stage;
 .quit
 EOF
 
-rm "$tmp_stat"
+rm "$tmp_fn" "$tmp_fn_check" "$tmp_stat"
 }
 
 
@@ -155,8 +147,14 @@ EOF
 hash_files() {
 if [ -s "$1" ]
 then
-< "$1" tr '\n' '\0' | xargs -0 -n 100 -P 1 $sha512_make \
-    | sed -E 's/^SHA512 \((.*)\) = /\1|/' > "$2"
+    if [ "$os" = Linux ]
+    then
+        < "$1" tr '\n' '\0' | xargs -0 -n 100 -P 1 sha512sum --tag \
+            | sed -E 's/^SHA512 \((.*)\) = /\1|/' > "$2"
+    else
+        < "$1" tr '\n' '\0' | xargs -0 -n 100 -P 1 sha512 \
+            | sed -E 's/^SHA512 \((.*)\) = /\1|/' > "$2"
+    fi
 fi
 }
 
@@ -250,6 +248,15 @@ hash TEXT NOT NULL CHECK (Length(hash) = 128)
 
 CREATE INDEX idx_c_hash_result_hash ON c_hash_result(hash);
 
+CREATE TABLE c_to_copy
+(filename TEXT NOT NULL CHECK (filename <> '' AND filename NOT LIKE '%|%'
+    AND filename NOT LIKE '%' || x'0A' || '%'),
+hash TEXT NOT NULL CHECK (Length(hash) = 128) UNIQUE PRIMARY KEY
+);
+
+CREATE UNIQUE INDEX uidx_c_to_copy_fn ON c_to_copy(filename);
+
+
 END TRANSACTION;
 
 .quit
@@ -268,7 +275,6 @@ fi
 
 store_dir="$(cat .capybara_store_location)"
 
-bad_filenames '.'
 gather_metadata
 load_latest
 
@@ -349,15 +355,27 @@ $dot_settings
 DELETE FROM c_hash_result;
 .import $tmp_hash_result c_hash_result
 
+DELETE FROM c_to_copy;
+
+INSERT INTO c_to_copy
+(filename,
+hash)
+SELECT
+Min(a.filename),
+a.hash
+FROM c_hash_result AS a
+WHERE
+a.hash NOT IN (SELECT b.hash FROM c_data AS b)
+GROUP BY a.hash;
+
 .echo off
 .changes off
 .output $tmp_to_copy
 
 SELECT
-Min(filename),
+filename,
 hash
-FROM c_hash_result
-GROUP BY hash;
+FROM c_to_copy;
 
 .output
 
@@ -381,7 +399,7 @@ BEGIN TRANSACTION;
 
 INSERT INTO c_snapshot (snapshot_time) VALUES ($snapshot_time);
 
-INSERT INTO c_data (hash) SELECT hash FROM c_hash_result GROUP BY hash;
+INSERT INTO c_data (hash) SELECT hash FROM c_to_copy;
 
 INSERT INTO c_file
 (
@@ -633,15 +651,25 @@ then
     exit 1
 fi
 
-tmp_to_hash="$(mktemp)"
+tmp_fn="$(mktemp)"
+tmp_fn_check="$(mktemp)"
+
+find "$external_media_dir" -type f ! -empty -print0 > "$tmp_fn"
+
+< "$tmp_fn" tr -d '|\n' > "$tmp_fn_check"
+
+if ! cmp "$tmp_fn" "$tmp_fn_check"
+then
+    printf 'Error: capybara: Newline or pipe character in filename\n' 1>&2
+    rm "$tmp_status" "$tmp_fn" "$tmp_fn_check"
+    exit 1
+fi
+
 tmp_hash_result="$(mktemp)"
 tmp_to_hard_link="$(mktemp)"
 
-bad_filenames "$external_media_dir"
 
-find "$external_media_dir" -type f ! -empty > "$tmp_to_hash"
-
-hash_files "$tmp_to_hash" "$tmp_hash_result"
+hash_files "$tmp_fn" "$tmp_hash_result"
 
 load_latest
 
@@ -707,7 +735,8 @@ then
         "$tmp_media_dir"
 fi
 
-rm "$tmp_status" "$tmp_to_hash" "$tmp_hash_result" "$tmp_to_hard_link"
+rm "$tmp_status" "$tmp_fn" "$tmp_fn_check" "$tmp_hash_result" \
+    "$tmp_to_hard_link"
 
 
 ###############################################################################
