save

diff --git a/capybara b/capybara
--- a/capybara
+++ b/capybara
@@ -186,10 +186,21 @@ store_dir="$(cat .capybara_store_location)"
 
 snapshot_time="$(date '+%s')"
 
+tmp_bad_fn="$(mktemp)"
 tmp_stat="$(mktemp)"
 tmp_to_hash="$(mktemp)"
 tmp_hash_result="$(mktemp)"
 tmp_to_copy="$(mktemp)"
+
+find . -type f \( -name '*|*' -o -name '*
+*' \) > "$tmp_bad_fn"
+
+if [ -s "$tmp_bad_fn" ]
+then
+    printf 'Error: %s: Newline or pipe character in filename(s):\n' "$1" 1>&2
+    cat "$tmp_bad_fn" 1>&2
+    exit 1
+fi
 
 find . -type f -exec stat "$stat_option" "$stat_format" '{}' \; \
     | cut -c 3- > "$tmp_stat"
@@ -311,7 +322,7 @@ END TRANSACTION;
 .quit
 EOF
 
-rm "$tmp_stat" "$tmp_to_hash" "$tmp_hash_result" "$tmp_to_copy"
+rm "$tmp_bad_fn" "$tmp_stat" "$tmp_to_hash" "$tmp_hash_result" "$tmp_to_copy"
 
 
 ###############################################################################
